"""Modelo de datos inicial: las 8 tablas del MVP.

companies, users, employees, terminals, work_sessions, work_breaks,
clock_events y audit_logs, con sus constraints e índices. Ver
docs/modelo-de-datos.md.

Revisado a mano tras el autogenerate: los enumerados se crean como VARCHAR
con un único CHECK nombrado según la convención (ck_<tabla>_<columna>);
el autogenerate duplicaba ese CHECK con un nombre sin prefijo.

Revision ID: 6f9783778aab
Revises: 
Create Date: 2026-09-28 17:56:06.607627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f9783778aab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Europe/Madrid', nullable=False),
    sa.Column('max_shift_hours', sa.SmallInteger(), server_default=sa.text('16'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(name) <> ''", name=op.f('ck_companies_name_not_blank')),
    sa.CheckConstraint("btrim(timezone) <> ''", name=op.f('ck_companies_timezone_not_blank')),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_companies_slug_format')),
    sa.CheckConstraint('char_length(slug) BETWEEN 3 AND 50', name=op.f('ck_companies_slug_length')),
    sa.CheckConstraint('max_shift_hours BETWEEN 1 AND 24', name=op.f('ck_companies_max_shift_hours_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('slug', name=op.f('uq_companies_slug'))
    )
    op.create_table('employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('pin_lookup', sa.LargeBinary(), nullable=False),
    sa.Column('pin_key_version', sa.SmallInteger(), nullable=False),
    sa.Column('pin_generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(first_name) <> ''", name=op.f('ck_employees_first_name_not_blank')),
    sa.CheckConstraint("btrim(last_name) <> ''", name=op.f('ck_employees_last_name_not_blank')),
    sa.CheckConstraint("dni ~ '^[A-Z0-9]+$'", name=op.f('ck_employees_dni_format')),
    sa.CheckConstraint('octet_length(pin_lookup) = 32', name=op.f('ck_employees_pin_lookup_length')),
    sa.CheckConstraint('pin_key_version >= 1', name=op.f('ck_employees_pin_key_version_positive')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employees_company_id_companies'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_employees_company_id_id')),
    sa.UniqueConstraint('company_id', 'pin_lookup', name=op.f('uq_employees_company_id_pin_lookup'))
    )
    op.create_index('uq_employees_company_id_dni', 'employees', ['company_id', 'dni'], unique=True, postgresql_where=sa.text('dni IS NOT NULL'))
    op.create_table('terminals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(name) <> ''", name=op.f('ck_terminals_name_not_blank')),
    sa.CheckConstraint('octet_length(token_hash) = 32', name=op.f('ck_terminals_token_hash_length')),
    sa.CheckConstraint('revoked_at IS NULL OR NOT active', name=op.f('ck_terminals_revoked_is_inactive')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_terminals_company_id_companies'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terminals')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_terminals_company_id_id')),
    sa.UniqueConstraint('company_id', 'name', name=op.f('uq_terminals_company_id_name')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_terminals_token_hash'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=14), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'PLATFORM_ADMIN') = (company_id IS NULL)", name=op.f('ck_users_company_matches_role')),
    sa.CheckConstraint("btrim(email) <> ''", name=op.f('ck_users_email_not_blank')),
    sa.CheckConstraint("btrim(full_name) <> ''", name=op.f('ck_users_full_name_not_blank')),
    sa.CheckConstraint("role IN ('ADMIN', 'MANAGER', 'PLATFORM_ADMIN')", name=op.f('ck_users_role')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=6), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(actor_type = 'USER') = (actor_user_id IS NOT NULL)", name=op.f('ck_audit_logs_actor_user_matches_type')),
    sa.CheckConstraint("action ~ '^[A-Z][A-Z_]*$'", name=op.f('ck_audit_logs_action_format')),
    sa.CheckConstraint("actor_type IN ('USER', 'SYSTEM')", name=op.f('ck_audit_logs_actor_type')),
    sa.CheckConstraint("entity_type ~ '^[a-z][a-z_]*$'", name=op.f('ck_audit_logs_entity_type_format')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_logs_company_id_companies'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_company_id_created_at', 'audit_logs', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id_created_at', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('work_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=12), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'CLOSED' OR ended_at IS NOT NULL", name=op.f('ck_work_sessions_closed_has_end')),
    sa.CheckConstraint("status <> 'OPEN' OR ended_at IS NULL", name=op.f('ck_work_sessions_open_has_no_end')),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED', 'NEEDS_REVIEW', 'VOIDED')", name=op.f('ck_work_sessions_status')),
    sa.CheckConstraint('ended_at IS NULL OR ended_at > started_at', name=op.f('ck_work_sessions_ended_after_started')),
    sa.ForeignKeyConstraint(['company_id', 'employee_id'], ['employees.company_id', 'employees.id'], name=op.f('fk_work_sessions_company_id_employee_id_employees'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_work_sessions_company_id_companies'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_sessions')),
    sa.UniqueConstraint('company_id', 'employee_id', 'id', name=op.f('uq_work_sessions_company_id_employee_id_id')),
    sa.UniqueConstraint('company_id', 'id', name=op.f('uq_work_sessions_company_id_id'))
    )
    op.create_index('ix_work_sessions_company_id_employee_id_needs_review', 'work_sessions', ['company_id', 'employee_id'], unique=False, postgresql_where=sa.text("status = 'NEEDS_REVIEW'"))
    op.create_index('ix_work_sessions_company_id_employee_id_work_date', 'work_sessions', ['company_id', 'employee_id', 'work_date'], unique=False)
    op.create_index('ix_work_sessions_company_id_work_date', 'work_sessions', ['company_id', 'work_date'], unique=False)
    op.create_index('uq_work_sessions_employee_id_open', 'work_sessions', ['employee_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('clock_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('terminal_id', sa.Uuid(), nullable=False),
    sa.Column('work_session_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=11), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.CheckConstraint("event_type IN ('CLOCK_IN', 'BREAK_START', 'BREAK_END', 'CLOCK_OUT')", name=op.f('ck_clock_events_event_type')),
    sa.ForeignKeyConstraint(['company_id', 'employee_id'], ['employees.company_id', 'employees.id'], name=op.f('fk_clock_events_company_id_employee_id_employees'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'terminal_id'], ['terminals.company_id', 'terminals.id'], name=op.f('fk_clock_events_company_id_terminal_id_terminals'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'employee_id', 'work_session_id'], ['work_sessions.company_id', 'work_sessions.employee_id', 'work_sessions.id'], name='fk_clock_events_company_id_employee_id_work_session_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_clock_events_company_id_companies'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clock_events')),
    sa.UniqueConstraint('terminal_id', 'idempotency_key', 'event_type', name=op.f('uq_clock_events_terminal_id_idempotency_key_event_type'))
    )
    op.create_index('ix_clock_events_company_id_employee_id_occurred_at', 'clock_events', ['company_id', 'employee_id', 'occurred_at'], unique=False)
    op.create_index('ix_clock_events_company_id_terminal_id_occurred_at', 'clock_events', ['company_id', 'terminal_id', 'occurred_at'], unique=False)
    op.create_table('work_breaks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('work_session_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR ended_at > started_at', name=op.f('ck_work_breaks_ended_after_started')),
    sa.ForeignKeyConstraint(['company_id', 'work_session_id'], ['work_sessions.company_id', 'work_sessions.id'], name=op.f('fk_work_breaks_company_id_work_session_id_work_sessions'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_work_breaks_company_id_companies'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_breaks'))
    )
    op.create_index('ix_work_breaks_work_session_id_started_at', 'work_breaks', ['work_session_id', 'started_at'], unique=False)
    op.create_index('uq_work_breaks_work_session_id_open', 'work_breaks', ['work_session_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_work_breaks_work_session_id_open', table_name='work_breaks', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index('ix_work_breaks_work_session_id_started_at', table_name='work_breaks')
    op.drop_table('work_breaks')
    op.drop_index('ix_clock_events_company_id_terminal_id_occurred_at', table_name='clock_events')
    op.drop_index('ix_clock_events_company_id_employee_id_occurred_at', table_name='clock_events')
    op.drop_table('clock_events')
    op.drop_index('uq_work_sessions_employee_id_open', table_name='work_sessions', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index('ix_work_sessions_company_id_work_date', table_name='work_sessions')
    op.drop_index('ix_work_sessions_company_id_employee_id_work_date', table_name='work_sessions')
    op.drop_index('ix_work_sessions_company_id_employee_id_needs_review', table_name='work_sessions', postgresql_where=sa.text("status = 'NEEDS_REVIEW'"))
    op.drop_table('work_sessions')
    op.drop_index('ix_audit_logs_entity_type_entity_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_company_id_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('terminals')
    op.drop_index('uq_employees_company_id_dni', table_name='employees', postgresql_where=sa.text('dni IS NOT NULL'))
    op.drop_table('employees')
    op.drop_table('companies')
    # ### end Alembic commands ###
